local status_ok, indent_blankline = pcall(require, 'indent_blankline')
if not status_ok then
  vim.notify 'Error requiring indent_blankline'
  return
end

indent_blankline.setup {
  space_char_blankline = ' ',
  show_current_context = true,
  show_current_context_start = true,
  -- "^func",
  -- "^if",
  -- "argument_list",
  -- "arguments",
  -- "class",
  -- "dictionary",
  -- "do_block"
  -- "element",
  -- "except",
  -- "for",
  -- "method",
  -- "object",
  -- "table",
  -- "try",
  -- "tuple",
  -- "while",
  -- "with",
  context_patterns = {
    '^else',
    '^for',
    '^func',
    '^if',
    '^object',
    '^table',
    '^while',
    'argument_list',
    'arguments',
    'catch_clause',
    'class',
    'dictionary',
    'do_block',
    'element',
    'else_clause',
    'if_statement',
    'except',
    'for',
    'func_literal',
    'function',
    'import_statement',
    'jsx_element',
    'jsx_self_closing_element',
    'method',
    'object',
    'operation_type',
    'table',
    'try',
    'try',
    'tuple',
    'while',
    'with',
  },
  char_highlight_list = {
    'IndentBlanklineIndent1',
    'IndentBlanklineIndent2',
    'IndentBlanklineIndent3',
    'IndentBlanklineIndent4',
    'IndentBlanklineIndent5',
    'IndentBlanklineIndent6',
  },
}
